FROM golang:1.26-alpine

LABEL org.opencontainers.image.title = "env-arg-demo"
LABEL org.opencontainers.image.version="1.0.0"

WORKDIR /app

# ARG — аргумент сборки. Доступен только при сборке.
ARG VERSION=dev
ARG TARGETOS=linux
ARG TARGETARCH=amd64

# ENV — переменная окружения. Остаётся в образе.
ENV APP_ENV=production
ENV PORT=8080

COPY . .

# Передаём VERSION в бинарник через ldflags.
# Используем ARG для cross-compile.
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build \
    -ldflags="-s -w -X main.version=${VERSION}" \
    -o server .

EXPOSE 8080

CMD ["./server"]    