syntax = "proto3";

package user.v1;

option go_package ="github.com/Kefir4c/go-knowledge-base\roadmap\06-web-api\6.6_gRPC\1.2_proto;protov1";

import "google/protobuf/timestamp.proto";

message ChatMessage {
  string room = 1;                // комната, к которой относится сообщение
  string user_id = 2;             // ID отправителя
  string text = 3;               // текст сообщения (может содержать команду)
  google.protobuf.Timestamp sent_at = 4;
}

service ChatService {
  rpc Chat (stream ChatMessage) returns (stream ChatMessage) {}
}